before:
  hooks:
  - go mod tidy
  - go generate ./...
  - sh scripts/completions.sh
  - sh scripts/manpages.sh
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  ldflags:
  - -X 'github.com/tantalor93/regatta-client/cmd.Version={{.Version}}-{{ .Os }}-{{ .Arch }}'
archives:
- id: regatta-client
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md
  - completions/*
  - manpages/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
brews:
- tap:
    owner: tantalor93
    name: homebrew-regatta-client
  folder: Formula
  homepage: https://github.com/Tantalor93/regatta-client
  install: |-
    bin.install "regatta-client"
    bash_completion.install "completions/regatta-client.bash" => "_regatta-client"
    zsh_completion.install "completions/regatta-client.zsh" => "_regatta-client"
    man1.install Dir["manpages/*.1"]
dockers:
- use: docker
  id: regatta-client
  dockerfile: "Dockerfile-goreleaser"
  image_templates:
  - "ghcr.io/tantalor93/regatta-client:{{ .Tag }}"
  - "ghcr.io/tantalor93/regatta-client:v{{ .Major }}"
  - "ghcr.io/tantalor93/regatta-client:v{{ .Major }}.{{ .Minor }}"
  - "ghcr.io/tantalor93/regatta-client:latest"
